os: Windows Server 2012 R2
platform:
  - x64

environment:
  matrix:
    - name: unit-tests-ruby-2.3.3
      ruby_version: "23"
    - name: unit-tests-ruby-2.4.4
      ruby_version: "24"
    - name: unit-tests-ruby-2.5.1
      ruby_version: "25"
    - name: functional-tests-1
      ruby_version: "25"
    - name: functional-tests-2
      ruby_version: "25"
    - name: functional-tests-3
      ruby_version: "25"
clone_folder: c:\projects\inspec
clone_depth: 1
skip_tags: true
branches:
  only:
    - master

cache:
  - vendor/bundle -> appveyor.yml

install:
  - systeminfo
  - winrm quickconfig -q
  - SET PATH=C:\Ruby%ruby_version%\bin;%PATH%
  - echo %PATH%
  - ruby --version
  - gem --version
  - bundler --version
  - ruby -r rubygems -e "p Gem.path"

build_script:
  - bundle install --path=vendor/bundle --without integration tools maintenance deploy
  - if not exist C:\tmp mkdir C:\tmp

test_script:
  - SET SPEC_OPTS=--format progress
  - bundle exec rake

for:
  -
    matrix:
      only:
        - name: functional-tests-1
    test_script:
      - SET SPEC_OPTS=--format progress
      - SET WORKER_NUMBER=1
      - bundle exec rake test:functional:windows
  -
    matrix:
      only:
        - name: functional-tests-2
    test_script:
      - SET SPEC_OPTS=--format progress
      - SET WORKER_NUMBER=2
      - bundle exec rake test:functional:windows
  -
    matrix:
      only:
        - name: functional-tests-3
    test_script:
      - SET SPEC_OPTS=--format progress
      - SET WORKER_NUMBER=3
      - bundle exec rake test:functional:windows
